### ISSUE TITLE
Проблема с модами

### ISSUE THREAD

**Issue by GrimJouw777** [tera-classic-toolbox/tera-toolbox-akeron#1]
При выборе персонажа появляются ошибки S_LOGIN, S_SPAWN_USER на модах. Как можно исправить? Работает только авто-лут.

Хотел написать в дискорд, но ссылка не работает.

**Comment by justkeepquiet** [comment]
Многие моды само собой работать не будут, так как изменения достаточно существенные, относительно даже самого старого патча, на который выходила тера-прокси. По данному вопросу лучше написать мне в дискорд JKQ#5649.

**Comment by GrimJouw777** [comment]
Хорошо, отправил запрос
