### ISSUE TITLE
ToolBox with VPN

### ISSUE THREAD

**Issue by COSYoff** [tera-classic-toolbox/tera-toolbox-akeron#3]
Привет! Есть ли возможность заставить работать коробку с включенным VPN?

**Comment by justkeepquiet** [comment]
Привет. По данному вопросу лучше обратиться в тех. поддержку сервиса, который предоставил VPN.
В целом нет никакой проблемы с работой тулбокса под VPN.

**Comment by COSYoff** [comment]
Не думаю, что проблема в VPN, т.к., только с ним я могу зайти в игру.

Но стоит мне включить коробку и попытаться зайти в игру, то просто пропадает лаунчер и игра не запускается. Выключаю VPN и игра запускается. Появляется 2-а сервера: с коробкой и дефолтный, но зайти я на них не могу. Включаю VPN - могу зайти на дефолтный сервер, а сервер с коробкой пропадает.

Раньше, когда TTC и Shinra юзались отдельно от прокси, была такая же проблема, но ее можно было решить.
Просто прописывали IP от VPN, где-то в настройках TTC или Shinra.
Может с коробкой тоже можно так поступить?

**Comment by justkeepquiet** [comment]
Очевидно, проблема заключается в том, что тулбокс не заворачивается в VPN. Где-либо прописать IP нельзя, так как тулбокс инжектится в процесс теры для подмены SLS (списка серверов). Вероятно программа VPN-клиента мешает работе либо этого инжекта, либо просто не подхватывает (не видит тулбокс). Поэтому по данному вопросу все-таки нужно обратиться в службу поддержки сервиса. Что касается нашей практики, то каких-либо проблем с использованием VPN не было, в том числе с ExitLag и другими подобными сервисами.
