### ISSUE TITLE
After today's patch the client its not able to log in

### ISSUE THREAD

**Issue by Reny900** [tera-classic-toolbox/tera-toolbox-akeron#5]
with no error in console log. On clicking refresh server list, akeron entry simply disappears

**Comment by justkeepquiet** [comment]
The Toolbox is currently not working due to changes in encryption on the Akeron server. Follow the news.

**Comment by waunero** [comment]
I sincerely wish you good luck in fixing it. I don't see the point of playing without Shinra.

**Comment by salabear** [comment]
any chance it will work?

**Comment by justkeepquiet** [comment]
> I don't see the point of playing without Shinra.

For this question, you need to contact the Akeron discord.

**Comment by waunero** [comment]
Will it comeback?

**Comment by Reny900** [comment]
100% no. Its up to akeron staff team now to keep up with their own promises:

![image](https://user-images.githubusercontent.com/19189602/233016783-2ea6b889-df0a-4012-a444-8d80d34f7064.png)
****

posted on : — 09/04/2023 23:58

**Comment by waunero** [comment]
Ah, thanks. I can finally delete this server.
